### ISSUE TITLE
Moving subdomain into defaults

### ISSUE THREAD

**Issue by d4rky-pl** [jeanmask/subdomain#2]
Rather than creating additional parameter to Route::set(), I believe you should move subdomain into defaults so it'd look like this:

```
Route::set('subdomain', '(<controller>(/<action>(/<id>)))', NULL)
    ->defaults(array(
        'subdomain' => array('*'),
        'controller' => 'test',
        'action'     => 'wildcard',
    ));
```

In my opinion it adds readability.

**Comment by zackperdue** [comment]
btw, does this work with 3.2 yet?

**Comment by jeanmask** [comment]
@zackperdue, yes, work with 3.2.

@d4rky-pl thanks for the tip, the default method is intended to set the standard route only (except for subdomain), in my opinion would be confusing, how about creating a new method? look

``` php
Route::set('subdomain', '(<controller>(/<action>(/<id>)))', NULL)
    ->subdomain(array('*'))
    ->defaults(array(
        'controller' => 'test',
        'action'     => 'wildcard',
    ));
```

**Comment by d4rky-pl** [comment]
Hey, that sounds good!

I definitely agree. Using the fourth parameter for Route::set() was also confusing, but a new method is definitely something worth consideration.

I'm also thinking if it wouldn't be good to simply cast the parameter to array ($this->_subdomain = (array) $subdomain;), therefore allowing subdomain("_") to work as well as subdomain(array("_")) (also allowing to pass objects implementing ArrayIterator). Decision is yours.

**Comment by jeanmask** [comment]
Thanks for the tip, I will consider your ideas. :)

**Comment by jeanmask** [comment]
I added the new features suggested and others, see:
https://github.com/jeanmask/subdomain/tree/3.2/develop

test and tell me what you think.

thanks ;)

**Comment by jeanmask** [comment]
this feature has added on 3.2/master :D

**Comment by d4rky-pl** [comment]
Yay! Too bad I'm too busy to actually see how it works :(

**Comment by jeanmask** [comment]
that bad when you have time then see, thank you!
