### ISSUE TITLE
Class 'Request' not found

### ISSUE THREAD

**Issue by grigrigory** [jeanmask/subdomain#3]
Installed this module but receive the following fatal error:

Fatal error: Class 'Request' not found in Z:\home\project\www\system\classes\kohana\kohana\exception.php on line 159

Kohana 3.2

**Comment by jeanmask** [comment]
you have installed other modules?
please tell me your system config ( SO, version e etc... )

**Comment by JDStraughan** [comment]
This seems to be an issue with the params not matching the Request::factory() method in core.  See https://github.com/jeanmask/subdomain/pull/4 for patch.
