### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by zackperdue** [jeanmask/subdomain#5]
Do i need to configure any actual subdomains through cpanel/virtual hosts to use this? 

Or is this just "simulation" a subdomain?

Thanks, i got the error worked out from your recent pull request.

**Comment by jeanmask** [comment]
http://steinsoft.net/index.php?site=programming/articles/apachewildcarddomain

**Comment by zackperdue** [comment]
Worked perfect, thanks m8

**Comment by jeanmask** [comment]
;)
